<?php
// utils/documentEmail.php
// Shared validation and audit helpers for emailed quotation, proforma, invoice and receipt PDFs.

declare(strict_types=1);

/**
 * Escape document content inserted into HTML email templates.
 */
function emailHtml(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

/**
 * Produce a safe attachment filename from the system's document number.
 */
function documentPdfFilename(string $type, string $documentNumber): string
{
    $labels = [
        'quotation' => 'Quotation',
        'proforma'  => 'Proforma',
        'invoice'   => 'Invoice',
        'receipt'   => 'Receipt',
        'credit_note' => 'Credit_Note',
    ];

    $label = $labels[$type] ?? 'Document';
    $safeNumber = preg_replace('/[^A-Za-z0-9_-]+/', '_', $documentNumber) ?: 'Document';

    return "Otelex_{$label}_{$safeNumber}.pdf";
}

/**
 * Validate the PDF generated by the authenticated frontend before passing it to PHPMailer.
 *
 * The attachment is never stored permanently on the server. PHP keeps it in the request's
 * temporary upload directory only for the duration of the mail send.
 *
 * @return array{path:string,name:string,size:int}
 * @throws Exception
 */
function requireDocumentPdfUpload(string $type, string $documentNumber): array
{
    if (!isset($_FILES['pdf_attachment']) || !is_array($_FILES['pdf_attachment'])) {
        throw new Exception('Please attach the generated PDF document before sending.', 422);
    }

    $upload = $_FILES['pdf_attachment'];
    $error = (int) ($upload['error'] ?? UPLOAD_ERR_NO_FILE);

    if ($error !== UPLOAD_ERR_OK) {
        if (in_array($error, [UPLOAD_ERR_INI_SIZE, UPLOAD_ERR_FORM_SIZE], true)) {
            throw new Exception('The PDF attachment is too large to send.', 422);
        }

        throw new Exception('The PDF attachment could not be uploaded. Please try again.', 422);
    }

    $tmpPath = (string) ($upload['tmp_name'] ?? '');
    $size = (int) ($upload['size'] ?? 0);
    $maxSize = 10 * 1024 * 1024; // 10MB

    if ($tmpPath === '' || !is_uploaded_file($tmpPath)) {
        throw new Exception('Invalid PDF upload received.', 422);
    }

    if ($size < 5 || $size > $maxSize) {
        throw new Exception('The PDF attachment must not exceed 10MB.', 422);
    }

    $signature = file_get_contents($tmpPath, false, null, 0, 5);
    if ($signature !== '%PDF-') {
        throw new Exception('Only a valid PDF document may be attached.', 422);
    }

    // Fileinfo is optional on some shared hosting plans; the PDF file signature above is
    // always checked. When Fileinfo is available, use it as an additional MIME check.
    if (class_exists('finfo')) {
        $finfo = new finfo(FILEINFO_MIME_TYPE);
        $mimeType = (string) $finfo->file($tmpPath);
        $acceptedMimes = ['application/pdf', 'application/x-pdf', 'application/octet-stream'];

        if (!in_array($mimeType, $acceptedMimes, true)) {
            throw new Exception('Only a valid PDF document may be attached.', 422);
        }
    }

    return [
        'path' => $tmpPath,
        'name' => documentPdfFilename($type, $documentNumber),
        'size' => $size,
    ];
}

/**
 * Record an email delivery attempt. A logging failure must not make the user resend an email
 * that was already successfully delivered; migration/setup errors are therefore logged only.
 */
function recordDocumentEmailLog(mysqli $conn, array $data): void
{
    try {
        $statement = $conn->prepare(
            'INSERT INTO document_email_logs
                (document_type, document_id, document_number, recipient_email, email_subject,
                 attachment_name, attachment_size, delivery_status, failure_reason, sent_by)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
        );

        if (!$statement) {
            throw new RuntimeException($conn->error);
        }

        $documentType = (string) $data['document_type'];
        $documentId = (int) $data['document_id'];
        $documentNumber = (string) $data['document_number'];
        $recipientEmail = (string) $data['recipient_email'];
        $subject = (string) $data['email_subject'];
        $attachmentName = (string) ($data['attachment_name'] ?? '');
        $attachmentSize = (int) ($data['attachment_size'] ?? 0);
        $deliveryStatus = (string) $data['delivery_status'];
        $failureReason = isset($data['failure_reason'])
            ? substr((string) $data['failure_reason'], 0, 250)
            : null;
        $sentBy = (int) $data['sent_by'];

        $statement->bind_param(
            'sissssissi',
            $documentType,
            $documentId,
            $documentNumber,
            $recipientEmail,
            $subject,
            $attachmentName,
            $attachmentSize,
            $deliveryStatus,
            $failureReason,
            $sentBy
        );
        $statement->execute();
        $statement->close();
    } catch (Throwable $logError) {
        error_log('Document Email Log Error: ' . $logError->getMessage());
    }
}

/**
 * Use consistent public responses for document-email routes without leaking SMTP internals.
 */
function respondDocumentEmailFailure(Throwable $error, string $context): void
{
    error_log($context . ': ' . $error->getMessage());

    $code = (int) $error->getCode();
    $isClientError = in_array($code, [400, 403, 404, 405, 409, 422], true);

    http_response_code($isClientError ? $code : 500);
    echo json_encode([
        'status' => 'failed',
        'message' => $isClientError
            ? $error->getMessage()
            : 'The document email could not be sent right now. Please try again.',
    ]);
}
